---
title: ""
date: last-modified
---

```{r}
#| label: libraries & setup

source('R/_libraries.R')
```

```{r}
#| label: necessary functions

#----------------------------------------------------------------------------------------
#' Custom function to retrieve the codebook URL
#' @param table Character. The table where variable information is needed.
#' @returns Full URL to CDC data documentation, codebook, & frequencies.
get_url <- function(table) {
  paste0(
    "https://wwwn.cdc.gov",
    nhanesManifest() |> 
      filter(Table == table) |> 
      pull(DocURL)
  ) |> 
  message()
}

#----------------------------------------------------------------------------------------
#' Custom wrapped function to nhanesA::nhanesSearch for concise output
#' @param var Character. Term or phrase to search
#' @returns Smaller output dataset
term_search <- function(var) {
  nhanesA::nhanesSearch(var, ignore.case = TRUE) |> 
  select(1:3, Begin.Year) |> 
  arrange(desc(`Begin.Year`), `Variable.Name`)
}

#----------------------------------------------------------------------------------------
#' Custom wrapped function to nhanes::nhanesSearchVarName for concise output
#' @param var Character. Variable name
#' @returns Smaller output dataset
var_search <- function(var) {
  nhanesA::nhanesSearchVarName(stringr::str_to_upper(var))
}

#----------------------------------------------------------------------------------------
#' Function to pull all datasets with the same base name
#' @param nhanes_table Character. NOT case-sensitive! Lowercase is allowed.
#' @param selected_variables Character vector. Default is NULL to grab all variables 
#' from the dataset. Do not use `everything()`... just don't enter an argument value.
#' @param save Logical. Save as new .rda and .parquet files. Default is TRUE
#' @returns Tibble of datasets across cycles; using `bind_rows()`.
pull_nhanes <- function(nhanes_table, selected_variables = NULL, save = TRUE) {

  nhanes_table <- stringr::str_to_upper(nhanes_table)
  message(sprintf('\nDataset: %s', nhanes_table))

  # Starting with B through L, skipping K
  table_suffixes <- c(LETTERS[2:10], LETTERS[12])

  start_dfr <- tibble(
    # Append the suffix to tables. First table has no letter suffix.
    # Will create something like DEMO_B & LAB_X
    code = c(nhanes_table, paste0(nhanes_table, '_', table_suffixes)),
    # The data for 2019-2020 was not collected the same way. See full docs.
    # This creates years: 1999-2017 & 2021
    year = c(seq(1999, 2017, by = 2), 2021)
  )

  # Initialize dataset
  combined_data <- tibble()

  for (i in seq_len(nrow(start_dfr))) {
    code <- start_dfr$code[i]  # the dataset name with suffix
    yr   <- start_dfr$year[i]  # corresponding year

    message(sprintf('Processing NHANES data for year: %s', yr))
    data <- nhanes(code)

    # Skip if dataset doesn't exist
    if (is.null(data)) {
      message(sprintf('Dataset %s not available, skipping...', code))
      next
    }

    if (is.null(selected_variables)) {
      current_data <- data |> mutate(year = yr, .before = 1) |> janitor::clean_names()
    } else {
      # Select only certain variables if a vector was passed
      current_data <- data |> 
        select(any_of(stringr::str_to_upper(selected_variables))) |> 
        mutate(year = yr, .before = 1) |> janitor::clean_names()
    }

    # browser()

    if (nrow(combined_data) == 0) {
      combined_data <- current_data
    } else {
      combined_data <- tryCatch({
        bind_rows(combined_data, current_data)
      }, error = function(e) {
        # Previous attmempts to combine data from multiple cycles has led to type
        # mismatching: one was factor while the other was character, you get the point...
        # Find the common variables and attempt to harmonize types
        common_cols <- intersect(names(combined_data), names(current_data))

        for (col in common_cols) {
          if (col == 'year') next

          existing_var_type <- typeof(combined_data[[col]])
          entering_var_type <- typeof(current_data[[col]])

          if (existing_var_type != entering_var_type) {
            message(sprintf(
              'Type mismatch in %s: %s vs %s... converting types now...', 
              col, existing_var_type, entering_var_type
            ))
            num_types <- c('double', 'integer')
            if (existing_var_type %in% num_types & entering_var_type %in% num_types) {
              combined_data[[col]] <- as.double(combined_data[[col]])
              current_data[[col]]  <- as.double(current_data[[col]])
            } else {
              combined_data[[col]] <- as.character(combined_data[[col]])
              current_data[[col]]  <- as.character(current_data[[col]])
            }
          }
        }

        bind_rows(combined_data, current_data)
      })
    }
  }

  mapped_dfr <- combined_data |> 
    mutate(
      year = as.integer(year),
      seqn = as.integer(seqn)
    )
  
  # Assign the dataset name
  assign(tolower(nhanes_table), mapped_dfr)

  if (save) {
    # Save the data in data/raw:
    if (!fs::dir_exists('data/raw/R')) {
      fs::dir_create('data/raw/R', recurse = TRUE)
    }
    if (!fs::dir_exists('data/raw/parquet')) {
      fs::dir_create('data/raw/parquet', recurse = TRUE)
    }
    
    # Save as .rda file (the object name will match the table name)
    save(
      list = tolower(nhanes_table),
      file = sprintf('data/raw/R/%s.rda', tolower(nhanes_table))
    )

    # Save as .parquet
    arrow::write_parquet(
      mapped_dfr,
      sprintf('data/raw/parquet/%s.parquet', tolower(nhanes_table))
    )
  }

  message(
    sprintf(
      'Number of rows for %s: %s',
      nhanes_table,
      scales::comma(nrow(mapped_dfr))
    )
  )

  return(mapped_dfr)
}

#-------------------------------------------------------
#' Read the dataset files from the public NHANES storage:
#' @param dataset Character. NHANES dataset base name. Not case sensitive.
#' @param type Character. Either "parquet" (faster) or "rda".
#' @details This function downloads NHANES data file from nhanes.kylegrealis.com.
#' @examples
#' trigly <- read_r2('trigly')
#' acq <- read_r2('acq')
read_r2 <- function(dataset, type = 'parquet') {
  dataset <- tolower(dataset)
  message(sprintf('Loading: %s', toupper(dataset)))
  ds <- arrow::read_parquet(
    file = sprintf(
      # 'https://pub-0ecceb5aa4654213b72c34b6e0895355.r2.dev/%s.%s',
      'https://nhanes.kylegrealis.com/%s.%s',
      dataset,
      type
    )
  )
  assign(dataset, ds, envir = .GlobalEnv)
  message(sprintf('%s complete!', toupper(dataset)))
}

```

```{r}
#| label: interview / questionnaire tables

# demographics
demo <- pull_nhanes('demo')  # 113249

# acculturation
acq <- pull_nhanes('acq')  # 89381

# allergies
agq <- pull_nhanes('agq')  # 9822

# alcohol
alq <- pull_nhanes('alq')  # 59896

# audiometry
auq <- pull_nhanes('auq')  # 98785

# blood pressure & cholesterol questionnaire
bpq <- pull_nhanes('bpq')  # 72093

# cardiovascular health
cdq <- pull_nhanes('cdq')  # 36252

# cormorbidity functioning
cfq <- pull_nhanes('cfq')  # 7178

# consumer behavior
cbq <- pull_nhanes('cbq')  # 59842

# creatinine kinase
ckq <- pull_nhanes('ckq')  # 13528

# diabetes
diq <- pull_nhanes('diq')  # 108555

# dietary interview, individual food first day
dr1iff <- pull_nhanes('dr1iff')  # 1166975

# dietary interview, second day
dr2iff <- pull_nhanes('dr2iff')  # 1010395

# total nutrient intake, first day
dr1tot <- pull_nhanes('dr1tot')  # 85867

# total nutrient intake, second day
dr2tot <- pull_nhanes('dr2tot')  # 76105

# food codes -- REVISIT THIS LATER: NO SEQN VARIABLE
# drxfcd <- pull_nhanes('drxfcd')

# modification codes -- SAME AS ABOVE
# drxmcd <- pull_nhanes('drxmcd')

# substance use
duq <- pull_nhanes('duq')  # 41709

# dermatology
deq <- pull_nhanes('deq')  # 41880

# diet, behavior, & nutrition
dbq <- pull_nhanes('dbq')  # 113249

# disability
dlq <- pull_nhanes('dlq')  # 28242

# mental health -- depression screener
dpq <- pull_nhanes('dpq')  # 46833

# early childhood
ecq <- pull_nhanes('ecq')  # 41156

# food security
fsq <- pull_nhanes('fsq')  # 101316

# health insurance
hiq <- pull_nhanes('hiq')  # 113249

# hepatitis
heq <- pull_nhanes('heq')  # 35513

# current health status
hsq <- pull_nhanes('hsq')  # 99855

# hospital utilization & access to care
huq <- pull_nhanes('huq')  # 113249

# immunization
imq <- pull_nhanes('imq')  # 112881

# income
inq <- pull_nhanes('inq')  # 71775

# kidney conditions & urology
# 1999
kiq <- pull_nhanes('kiq')  # 4880
# 2001+
kiqu <- pull_nhanes('kiq_u')  # 58010

# prostate conditions
kiq_p <- pull_nhanes('kiq_p')  # 12652

# cancer questions
mcq <- pull_nhanes('mcq')  # 108555

# occupation
ocq <- pull_nhanes('ocq')  # 73344

# oral health
ohq <- pull_nhanes('ohq')  # 94979

# osteoporosis
osq <- pull_nhanes('osq')  # 39348

# pesticide use
puqmec <- pull_nhanes('puqmec')  # 64445

# physical activity -- individual activities
paqiaf <- pull_nhanes('paqiaf')  # 49784

# phyiscal functioning
pfq <- pull_nhanes('pfq')  # 93104

# prescription medication -- MULTIPLE ROWS PER PARTICIPANT
rxq_rx <- pull_nhanes('rxq_rx')  # 202009

# prescription medication -- drug information
# rxq_drug <- pull_nhanes('rxq_drug')

# physical activity
paq <- pull_nhanes('paq')  # 98969

# PSA follow-up
psq <- pull_nhanes('psq')  # 173

# respiratory health
rdq <- pull_nhanes('rdq')  # 68569

# reproductive health
rhq <- pull_nhanes('rhq')  # 39362

# sleep disorders
slq <- pull_nhanes('slq')  # 53202

# smoking
smq <- pull_nhanes('smq')  # 73889

# smoking -- household
smqfam <- pull_nhanes('smqfam')  # 113249

# smoking recent tobacco use
smqrtu <- pull_nhanes('smqrtu')  # 55138

# social support
ssq <- pull_nhanes('ssq')  # 14086

# sexual behavior
sxq <- pull_nhanes('sxq')  # 37137

# vision
viq <- pull_nhanes('viq')  # 24464

# weight history
whq <- pull_nhanes('whq')  # 72093

# weight history -- youth
whqmec <- pull_nhanes('whqmec')  # 10566
```

```{r}
#| label: examination tables

# albumin & creatinine
alb_cr <- pull_nhanes('alb_cr')  # 65958

# audiometry
aux <- pull_nhanes('aux')  # 22760

# audiometry -- accoustic reflex
auxar <- pull_nhanes('auxar')  # 101651

# more glucose, etc.
biopro <- pull_nhanes('biopro')  # 55138

# body measures
bmx <- pull_nhanes('bmx')  # 105626

# blood pressure
bpx <- pull_nhanes('bpx')  # 96766

# blood counts
cbc <- pull_nhanes('cbc')  # 73218

# --------------------------------------------------------------------------------------
# NOTE: bodyscan has repeated meaures until 2005+. Do not use the full bodyscan in the
# analysis, but use the body dataset instead!
# More info here: https://wwwn.cdc.gov/nchs/data/nhanes/public/2005/datafiles/dxx_d.htm
# bodyscan
dxx <- pull_nhanes('dxx')  # 57084

# Example if you'd like to randomly samply one observation.
# This will only affect 2005 since that is the only cycle with 
# repeated or imputed measures. Every other cycle is unaffected.
# CHOOSE WISELY!
#
# set.seed(305)
# dxx_red <- dxx |> 
#   group_by(seqn) |> 
#   slice_sample(n = 1)  # 29512
# --------------------------------------------------------------------------------------

# diabetes 2
ghb <- pull_nhanes('ghb')  # 55138

# glucose
glu <- pull_nhanes('glu')  # 27039

# cholesterol
hdl <- pull_nhanes('hdl')  # 64445

# hiv
hiv <- pull_nhanes('hiv')  # 26137

# cholesterol 2
tchol <- pull_nhanes('tchol')  # 64445

# tryglyceride
trigly <- pull_nhanes('trigly')  # 27039
```